### ISSUE TITLE
Reorganize root to "Components" and "Examples"

### ISSUE THREAD

**Issue by ryckmanat** [google/open-product-recovery#32]
Early on, we began separating everything into separate "opr-" folders based on the thinking that we might split these things out as separate repos at some point. Now, with our "monorepo" approach, it probably makes more sense to simplify the root structure. We discussed adding a "components" folder in src that would house subfolders for each independent npm package, and an "examples" folder that would house example implementations.

- [ ] Add "components" folder to root
- [ ] Add "components/platforms/" folder
- [ ] Add "examples" folder to root
- [ ] Move opr-models, opr-core, opr-sql-database, opr-dev-tools to components/
- [ ] Move opr-google-cloud to components/platforms/
- [ ] Move opr-example-serve and opr-example-server-gcp to examples/
- [ ] Rename opr-example-server folder to "local-starter"
- [ ] Rename opr-example-server-gcp to "gcp-cloudrun-postgres"

**Comment by johndayrichter** [comment]
How would you feel about these slight changes to that list:

1. We also add a platforms subdirectory. So opr-core, opr-sql-database and opr-models go in components/, and opr-google-cloud/ goes into platforms/. In the future, we'd also add opr-amazon-web-services and opr-microsoft-azure to platforms/
2. We call basic-starter local-starter, so that we use a <platform-description> naming convention

wdyt?

**Comment by ryckmanat** [comment]
Yeah - I like that - I'll edit the original list...
